#!/usr/bin/env node
/**
 * Render the workspace dependency graph into docs/dependency-graph.md.
 *
 * Mermaid rather than SVG on purpose: it needs no graphviz binary, renders
 * inline on GitHub, and diffs as text — so a structural change to the codebase
 * shows up as a readable diff in review instead of a binary blob.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "docs", "dependency-graph.md");
const SOURCES = ["shared/src", "web/src", "server/src"];

/** Folder-level, or 93 modules of detail drowns the shape we care about. */
const COLLAPSE = "^(shared|web|server)/src/[^/]+";

const depcruise = (args) =>
  execFileSync("pnpm", ["exec", "depcruise", ...SOURCES, "--config", ".dependency-cruiser.cjs", ...args], {
    cwd: ROOT,
    encoding: "utf8",
    maxBuffer: 32 * 1024 * 1024,
  });

// Only our own modules: node builtins and npm packages are noise in a diagram
// about how the three workspaces relate. `graph:check` still sees everything.
const diagram = depcruise([
  "--include-only",
  "^(shared|web|server)/",
  "--collapse",
  COLLAPSE,
  "--output-type",
  "mermaid",
]).trim();
const { summary } = JSON.parse(depcruise(["--output-type", "json"]));
const counted = `${summary.totalCruised} modules, ${summary.totalDependenciesCruised} dependencies, ${summary.error} rule violations.`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `# Dependency graph

Generated by \`pnpm graph\` — do not edit by hand.

Folder-level view of how the three workspaces depend on each other. The rules that
keep this shape honest live in \`.dependency-cruiser.cjs\` and are enforced by
\`pnpm graph:check\`: no cycles, \`web\` and \`server\` never import each other, and
\`shared\` stays a leaf so it can be the contract both sides import.

\`\`\`mermaid
${diagram}
\`\`\`

${counted}
`,
);

console.log(`wrote ${OUT}`);
